# XDG base directories
[ -z "${XDG_CACHE_HOME}" ] && XDG_CACHE_HOME="${HOME}/.cache" && export XDG_CACHE_HOME
[ -z "${XDG_CONFIG_HOME}" ] && XDG_CONFIG_HOME="${HOME}/.config" && export XDG_CONFIG_HOME
[ -z "${XDG_DATA_HOME}" ] && XDG_DATA_HOME="${HOME}/.local/share" && export XDG_DATA_HOME
[ -z "${XDG_STATE_HOME}" ] && XDG_STATE_HOME="${HOME}/.local/state" && export XDG_STATE_HOME

# Dotfile cleanup
[ -z "${GTK2_RC_FILES}" ] && GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc" && export GTK2_RC_FILES
[ -z "${WGETRC}" ] && WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc" && export WGETRC
